[package]
name = "abc276"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
itertools = "0.10.5"
proconio = { version = "*", features = ["derive"] }
superslice = "1.0.0"

[profile.release]
lto = true
panic = 'abort'
