[package]
name = "abc287"
version = "0.1.0"
edition = "2021"

# dependencies added to new project
[dependencies]
proconio = { version = "*", features = ["derive"] }
itertools = { version = "*" }

[profile.release]
lto = true
panic = 'abort'
